server:
  port: 8089
spring:
  application:
    name: app-server    # 项目名称尽量用小写
  jpa:
    database : MYSQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
      # hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:                           # 指定数据源
    #platform: h2                        # 指定数据源类型
    initialize: false # 是否执行schema 和 data 属性
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的insert脚本
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://120.25.146.138:33060/db_langrensha?useUnicode=true&characterEncoding=utf8
  kafka:
    bootstrap-servers: 120.25.146.138:9092
    consumer.group-id: test
    consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    consumer.value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer.value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true
#hystrix.command.default.execution.timeout.enabled: false
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000